README.md

Appended a slash ("/"), or the URL won't work.

Appended a slash ("/"), or the URL won't work.

---

build/build-changelog.sh
build/releash.sh
package.json

改动点:
- 增加 npm 发布脚本
- 增加 changelog 生成器

[new feature] 增加发布脚本

---

dist/field/index.wxml
dist/field/index.wxss
example/field/index.wxml

- 修复 Field 多行展示
- 增加 Field 模板中 placeholder 样式

[bug fix] Field: 修复多行展示样式

---

packages/field/index.js

- Field 组件，支持 Input 事件触发后，更改输入框内容

[new feature] Field: Input 事件支持升级

---

packages/tab/README.md
packages/toast/README.md
packages/toptips/README.md

Docs: 新增使用文档

---

example/pages/field/index.js
example/pages/field/index.wxml
packages/field/index.wxml

[new feature] Field:  增加 value 传入支持

---

packages/panel/README.md
packages/row/README.md
packages/steps/README.md
packages/switch/README.md
packages/tab/README.md

Docs: 增加组件使用文档

---

example/pages/dialog/index.js
example/pages/dialog/index.wxml
example/pages/popup/index.js
example/pages/popup/index.wxml
example/pages/popup/index.wxss
example/pages/toast/index.js
packages/dialog/README.md
packages/dialog/index.js
packages/dialog/index.pcss
packages/dialog/index.wxml
packages/icon/README.md
packages/index.js
packages/popup/README.md
packages/popup/index.pcss

- 重构 + 整理 Popup 组件
- 重构 + 整理 Dialog 组件
- icon 文档增加

[breaking change] Dialog Popup 重构

---

packages/dialog/index.js

[bugfix] Dialog: 修复自定义按钮时按钮点击回调问题

---

.github/PULL_REQUEST_TEMPLATE.md
packages/field/README.md

[improvement] Doc: 增加 Field 组件文档

---

example/pages/field/config.js
example/pages/field/index.js
example/pages/field/index.wxml
packages/field/README.md
packages/field/index.js
packages/field/index.wxml
packages/utils/index.js

- field 支持 form submit 支持
- field 增加 focus blur 事件回调

[improvement] Field: 新增 Form 支持

---

example/pages/tag/index.wxml
packages/tag/README.md

[improvement] Doc: 增加 tag 组件文档

---

example/pages/dashboard/config.js
example/pages/tag/index.wxml
packages/tag/index.pcss

- 修复 Tag 在未添加主题时，plain 样式展现问题
- 调整文档顺序

[bug fix] Tag: 修复展现问题

---

packages/popup/index.pcss

- 改动一
修改packages/popup/index.pcss，新增zan-popup、zan-popup--show的visibility属性。

[bug fix]Popup：修复弹出的container遮挡主页事件bug

---

example/pages/loadmore/index.wxml
packages/loadmore/README.md
packages/noticebar/README.md

[improvement] Doc: 新增使用文档

---

example/pages/panel/index.wxml
packages/panel/index.pcss

[improvement] 增加无边框的panel样式

---

packages/badge/index.pcss

[bug fix] Badge: 修复 badge 纵向对齐问题

---

example/pages/dashboard/config.js
example/pages/select/index.js
example/pages/select/index.wxml
packages/index.js
packages/select/README.md
packages/select/index.wxml
packages/toptips/README.md

- 新增 Select 组件支持 form 中 submit 使用
- 新增 Select 组件文档

[improvement] 新增 Select 组件支持 form 中 submit 使用

---

example/pages/actionsheet/index.js
packages/actionsheet/index.wxml

- actionsheet 新增 open-type 支持
#100

[new feature] Actionsheet: 新增 open-type 支持

---

packages/toptips/index.js

[bug fix] Toptips: 修复在控制台里的报错

---

example/pages/field/index.js
example/pages/field/index.wxml
example/pages/field/index.wxss

- Field: 示例中增加 picker-view 使用 #110

[improvement] Field: 示例中增加 picker-view 使用

---

packages/toptips/index.js
packages/toptips/index.pcss

- 修复 Toptips 在未显示时，下拉页面能看到红条的问题
- 改进 Toptips 默认 timer 值

[bug fix] Toptips: 修复未显示时，下拉页面展示问题

---

README.md
packages/actionsheet/README.md

[improvement]增加 Actionsheet 文档

---

example/pages/toast/index.js
example/pages/toast/index.wxml
packages/toast/README.md
packages/toast/index.js
packages/toast/index.pcss
packages/toast/index.wxml

[new feature] Toast: 支持图标展示

---

packages/noticebar/index.js
scripts/icons/fount-config.js

[bugfix] Noticebar: 修复元素查询返回空，导致报错的问题

---

example/pages/field/config.js
packages/field/README.md
packages/field/index.wxml

[new feature] Field: 新增 focus 自动聚焦属性

---

dist/actionsheet/index.js
dist/capsule/index.wxml
dist/field/index.js
dist/noticebar/index.js
dist/select/index.js
dist/stepper/index.js
dist/switch/index.js
dist/tab/index.js
package-lock.json
package.json
packages/capsule/index.wxml
packages/field/index.js
scripts/utils/build.js
scripts/utils/extracter.js

[improvement] 移除多余的日志信息

---

packages/dialog/index.pcss

[bugfix] Dialog: 修复弹窗被输入框文本覆盖的问题

---

example/pages/field/config.js
example/pages/field/index.wxml
packages/field/README.md
packages/field/index.wxml

[improvement] Field: 新增 disabled 属性支持

---

packages/noticebar/index.js

[bugfix] NoticeBar: 修复动画播放异常的问题

---

example/pages/badge/index.json
example/pages/badge/index.wxml
example/pages/badge/index.wxss
packages/badge/README.md
packages/badge/index.js
packages/badge/index.json
packages/badge/index.pcss
packages/badge/index.wxml
yarn.lock

重构badge为自定义组件
增加color, background-color, font-size, box-shadow配置

[refactor] 重构badge为自定义组件

---

example/pages/badge/index.json
example/pages/badge/index.wxml
example/pages/badge/index.wxss
example/pages/tab/index.js
example/pages/tab/index.json
example/pages/tab/index.wxml
example/pages/tab/index.wxss
packages/badge/README.md
packages/badge/index.js
packages/badge/index.json
packages/badge/index.pcss
packages/badge/index.wxml
packages/tab/README.md
packages/tab/index.js
packages/tab/index.json
packages/tab/index.wxml
yarn.lock

[refactor] Tab：升级到自定义组件

---

example/pages/cell/index.json
example/pages/cell/index.wxml
packages/cell-group/index.js
packages/cell-group/index.json
packages/cell-group/index.wxml
packages/cell/README.md
packages/cell/index.js
packages/cell/index.json
packages/cell/index.pcss
packages/cell/index.wxml

[Improvement] Cell：改写 cell 组件为自定义组件
- 新增 cell-group 组件
- cell 组件改写为自定义组件

[refactor] Cell：升级到自定义组件

---

packages/Panel/panel.js
packages/Panel/panel.json
packages/Panel/panel.wxml
packages/panel/README.md
packages/panel/index.pcss

[refactor] Panel: 升级到自定义组件

---

example/pages/field/config.js
example/pages/field/index.js
example/pages/field/index.json
example/pages/field/index.wxml
example/pages/icon/index.wxml
example/pages/stepper/index.js
example/pages/stepper/index.json
example/pages/stepper/index.wxml
packages/field/README.md
packages/field/index.js
packages/field/index.json
packages/field/index.pcss
packages/field/index.wxml
packages/stepper/README.md
packages/stepper/index.js
packages/stepper/index.json
packages/stepper/index.wxml

- Field组件迁移到自定义组件
- Stepper组件迁移到自定义组件

[refactor] Field & Stepper 自定义组件改造

---

example/pages/dialog/index.js
packages/dialog/index.wxml

[improvement] Dialog: 内容区支持换行展示

---

packages/panel/README.md
packages/switch/README.md
packages/switch/index.js
packages/switch/index.json
packages/switch/index.wxml

[refactor] Switch: 组件升级

---

packages/cell/index.wxml

[improvement] Cell: 移除组件运行时不使用的占位标签

---

example/pages/steps/index.json
example/pages/steps/index.wxml
packages/steps/README.md
packages/steps/index.js
packages/steps/index.json
packages/steps/index.wxml

[refactor] 重构steps为自定义组件
- steps组件源码
- example中的内容修改

 [refactor] Steps: 重构为自定义组件

---

README.md
example/pages/select/index.js
example/pages/select/index.json
example/pages/select/index.wxml
packages/select/README.md
packages/select/index.js
packages/select/index.pcss
packages/select/index.wxml

- 修复 select 示例代码
- 优化 readme 展示

[improvement] Doc: 修复文档展示

---

example/pages/btn/index.json
example/pages/btn/index.wxml
example/pages/dialog/index.json
example/pages/dialog/index.wxml
example/pages/popup/index.json
example/pages/popup/index.wxml
example/pages/toast/index.json
example/pages/toast/index.wxml
example/pages/toptips/index.wxml
packages/btn-group/index.js
packages/btn-group/index.json
packages/btn-group/index.wxml
packages/btn-group/index.wxss
packages/btn/index.js
packages/btn/index.pcss
packages/btn/index.wxml

[new feature] 新增 btn-group

---

example/pages/stepper/index.js
packages/stepper/README.md

[bug fix] Stepper: 文档错误

---

packages/badge/index.wxml

- 修复页面数据改变了以后，badge 中的数字不变的问题
#223

[bugfix] Badge: 修复页面数据改变了以后，badge 中的数字不变的问题

---

example/pages/toast/index.js
packages/toast/README.md
packages/toast/toast.js

[Improvement] Toast: 新增默认配置设置

---

packages/cell-group/index.js
packages/cell/index.js

- 修复 cell 在元素更新后，边框会不显示的问题
#234

[bugfix] Cell: 修复在元素更新后，边框会不显示的问题

---

example/pages/cell/index.js
example/pages/cell/index.wxml
packages/cell-group/index.js

- 修复 cell 中使用全局变量，导致部分 cell 边框不出现的问题

[bugfix] Cell: 修复部分cell边框不出现的问题

---

.github/PULL_REQUEST_TEMPLATE.md
doc.config.js
packages/btn/README.md

- 修复 btn 文档中的错误
- loading 组件放到基础组件的列表中

[bugfix] Doc: 修复文档错误

---

example/pages/dialog/index.js
packages/dialog/index.wxml

- 为Dialog中的Button加入了open-type的支持，并更新了相应的示例

[improvement] Dialog：使Dialog中的Button支持open-type，并更新了example文件夹中相应的Dialog示例

---

example/pages/cell/index.js
example/pages/cell/index.wxml
package-lock.json
packages/cell/index.js
packages/cell/index.wxml

[bugfix] Cell: 修复 cell 点击事情触发两次的问题

---

example/pages/stepper/index.js
example/pages/stepper/index.wxml
packages/stepper/README.md
packages/stepper/index.js

- 修复 stepper 组件不传 max 情况下，默认置灰的问题 #263 
- 修复 stepper 文档错误 #262

[bugfix] Stepper: 修复组件不传 max 情况下，默认置灰的问题

---

example/pages/cell/index.json
example/pages/stepper/index.js
example/pages/stepper/index.wxml
packages/cell-group/index.pcss
packages/cell/index.js
packages/cell/index.pcss
packages/cell/index.wxml
packages/stepper/README.md
packages/stepper/index.js

- 增加 cell 组件默认白色背景色
- cell 支持外部样式类

[improvement] Cell: 增加默认白色背景色

---

example/pages/steps/index.js
example/pages/steps/index.wxml
packages/steps/wxss/step.pcss

[bug fix]: Steps 修复2步完成样式 && 优化文档 #255

[bug fix]: Steps 修复2步样式 && 优化文档

---

packages/btn/index.wxml

[bug fix]: Button fix hover

---

example/pages/field/index.json
example/pages/field/index.wxml
packages/cell-group/index.js
packages/cell/index.js
packages/field/README.md
packages/field/index.js
packages/field/index.json
packages/field/index.pcss
packages/field/index.wxml

- 在组件中使用 zan-cell 自定义组件
- 优化列表形式的 Field

[improvement] Field: 优化在列表中输入框表现

---

packages/dialog/index.js

[bugfix] Dialog 修复使用dialog组件的页面切换路由时报错 (#289)

---

packages/dialog/data.js
packages/dialog/dialog.js

[bugfix] Dialog: 修复取消按钮只生效一次 @rex-zsd (#295)

---

example/pages/dashboard/config.js

修复 #309
- example中增加datetime-picker组件的入口

[bugfix] datetime-picker: 增加demo中datetime示例入口 @rex-zsd

---

example/pages/steps/index.wxml
example/pages/steps/index.wxss
packages/steps/README.md
packages/steps/index.js
packages/steps/index.wxml
packages/steps/wxss/vstep.pcss

#266 添加 icon-class, title-class, desc-class来扩展样式

[improvement] Steps: 扩展自定义class

---

packages/toptips/README.md
packages/toptips/index.js
packages/toptips/index.wxml
packages/toptips/toptips.js

修复 #317
- 把 index.js 中导出的 Toptips 函数移动到单独的 toptips.js 文件中
- 修复 backgroundColor 不生效的问题

[bugfix] Toptips: 修复toptips在自定义组件中引入报错的问题，backgroundColor不生效的问题

---

packages/btn/index.wxml

[improvement] Button: 透传disabled属性

---

packages/popup/README.md

[improvement] Doc: 优化 popup 遮罩层相关文档

---

packages/noticebar/index.js

修复 #279 #268
- 修复text动态更新后不会重新计算滚动的问题
- 计算滚动时不再抛出错误

[bugfix] Noticebar: 支持动态更新text

---

example/pages/toast/index.js
example/pages/toast/index.wxml
packages/toast/README.md
packages/toast/toast.js

[bugfix] Toast: 修复Toast组件的timeout不支持小于0的问题

---

packages/tab/index.js
packages/tab/index.wxml

[new feature] tab: 支持选中项自动滑动到中间位置

---

example/pages/toptips/index.js
packages/index.js

[bugfix] Toptips: 修复示例小程序的问题

---

packages/toast/toast.js

- 修复 toast 未传入 timeout 时不会自动关闭的问题

[bugfix] Toast: 修复未传入 timeout 时不会自动关闭的问题

---

doc.config.js
example/app.json
example/pages/dashboard/config.js
example/pages/radio/index.js
example/pages/radio/index.json
example/pages/radio/index.wxml
example/pages/radio/index.wxss
packages/checkbox/index.wxml
packages/radio/README.md
packages/radio/index.js
packages/radio/index.json
packages/radio/index.pcss
packages/radio/index.wxml

[new feature] 新增 Radio:
Projects: https://github.com/youzan/zanui-weapp/projects/1#card-5563146

[new feature] 新增 Radio

---

example/pages/field/index.wxml
package-lock.json
package.json
packages/field/index.js
scripts/utils/extracter.js

[breaking change] Field: 修复组件错误的事件参数

---

example/pages/dashboard/config.js

[improvement] Doc: 增加 tree-select DEMO

---

example/pages/search/index.js
example/pages/search/index.wxml
example/pages/search/index.wxss
packages/search/README.md
packages/search/index.js
packages/search/index.pcss
packages/search/index.wxml

添加input区域的插槽，可以像门店搜索那样插入picker，设置范围；
- slot名是input
- 添加picker 例子

[improvement]: search组件支持插槽功能

---

packages/common/README.md
packages/common/style/ellipsis.pcss

- 新增内置样式类van-multi-ellipsis--l2、van-multi-ellipsis--l3

[new feature] 新增内置样式类van-multi-ellipsis--l2、van-multi-ellipsis--l3

---

packages/actionsheet/index.pcss
packages/cell/README.md
packages/field/README.md
packages/field/index.js
packages/field/index.wxml

- Field组件增加titleWidth属性
- ActionSheet组件修复样式冲突

[improvement] Field：增加titleWidth属性

---

packages/cell/README.md
packages/field/README.md
packages/field/index.js

修复 #490 
- Cell 文档 titleWidth 类型更改为 String
- Field 文档、源码 titleWidth 类型更改为 String

[bugfix] Doc: 修复 Cell Field 组件 titleWidth 类型错误

---

packages/notify/README.md

- Notify 文档组件引入路径更新为 vant-weapp

[bugfix] Doc: notify 引入路径错误

---

docs/src/Preview.vue
example/app.json
example/config.js
example/pages/submit-bar/index.js
example/pages/submit-bar/index.json
example/pages/submit-bar/index.wxml
example/pages/submit-bar/index.wxss
packages/submit-bar/README.md
packages/submit-bar/index.js
packages/submit-bar/index.json
packages/submit-bar/index.pcss
packages/submit-bar/index.wxml

[new feature] SubmitBar: 增加submit-bar组件

---

.gitignore
example/pages/tab/index.wxml
packages/tab/README.md
packages/tabs/index.js
packages/tabs/index.wxml

-  feat(Tabs)：增加属性 border，默认值 false,不显示 tabs的外边框线
- .gitignore 添加 .history(ide 插件自动添加)文件忽略

[new feature] Tab: add border prop

---

packages/area/index.js

[bugfix] Area: 修复Area组件边界条件时报错

---

example/app.json
example/config.js
example/pages/radio/index.js
example/pages/radio/index.json
example/pages/radio/index.wxml
example/pages/radio/index.wxss
packages/radio-group/index.js
packages/radio-group/index.json
packages/radio-group/index.pcss
packages/radio-group/index.wxml
packages/radio/README.md
packages/radio/index.js
packages/radio/index.json
packages/radio/index.pcss
packages/radio/index.wxml

[new feature] Radio: 增加单选框组件

---

packages/radio-group/index.js
packages/radio/index.js

[bugfix] Radio: 修复单选框报错

---

example/pages/radio/index.json
example/pages/submit-bar/index.json
packages/submit-bar/index.js
packages/submit-bar/index.pcss
packages/submit-bar/index.wxml

修复 #631
- SubmitBar增加外部样式类bar-class
- SubmitBar修复未传price时仍显示总计
- SubmitBar样式优化，使价格不存在时slot可能占满左侧空间
- 修复Radio、SubmitBar的demo页标题错误

[bugfix] SubmitBar：优化提交订单栏

---

docs/src/Preview.vue
example/app.json
example/config.js
example/pages/checkbox/index.js
example/pages/checkbox/index.json
example/pages/checkbox/index.wxml
example/pages/checkbox/index.wxss
packages/checkbox-group/index.json
packages/checkbox-group/index.ts
packages/checkbox-group/index.wxml
packages/checkbox/README.md
packages/checkbox/index.json
packages/checkbox/index.less
packages/checkbox/index.pcss
packages/checkbox/index.ts
packages/checkbox/index.wxml

[new feature] Checkbox: 增加复选框组件

---

packages/card/README.md
packages/card/index.ts
packages/card/index.wxml

[new feature] Card: 卡片组件增加图片懒加载属性

---

example/pages/card/index.json
example/pages/card/index.wxml
packages/card/README.md
packages/card/index.less
packages/card/index.ts
packages/card/index.wxml

[new feature] Card: add originPrice prop、update style

---

packages/card/README.md
packages/card/index.ts
packages/card/index.wxml

- Card 组件增加 thumb-mode 属性，透传给原生 image 组件 mode 属性

[improvement] Card: add thumb-mode prop

---

packages/tabs/index.less
packages/tabs/index.wxml

[bugfix] Tabs: 修复Tabs组件card样式问题

---

packages/cell/index.less

[improvement] Cell: 解决外部样式类优先级问题

---

packages/cell/index.less
packages/cell/index.wxml

[improvement] Cell: 优化左右图标未对齐问题

---

package-lock.json
packages/tabs/index.wxml

修复 #762
- 修复Tabs组件为card样式时border颜色失效问题

[bugfix] Tabs: card type incorrect border color

---

example/pages/icon/index.js
packages/icon/index.less

[improvement] Icon: add card-o icon

---

example/pages/goods-action/index.wxml
packages/goods-action-button/index.ts
packages/goods-action-button/index.wxml
packages/goods-action-icon/index.ts
packages/goods-action-icon/index.wxml
packages/goods-action/README.md

修复 #793 
- 支持open-type等更多Button API

[new feature] GoodsAction: 支持open-type等更多Button API

---

packages/action-sheet/index.less
packages/action-sheet/index.wxml

[bugfix] ActionSheet: 修复背景色样式问题

---

packages/common/style/mixins/ellipsis.less

[bugfix]: autoprefixer remove ellipsis

---

packages/tab/index.ts
packages/tabs/index.ts

修复 #811 
- 修复动态设置tabs时底部划线样式问题

[bugfix] Tab: fix line incorrect style when set tabs async

---

example/app.json
example/config.js
example/pages/swipe-cell/index.js
example/pages/swipe-cell/index.json
example/pages/swipe-cell/index.wxml
example/pages/swipe-cell/index.wxss
packages/swipe-cell/README.md
packages/swipe-cell/index.json
packages/swipe-cell/index.less
packages/swipe-cell/index.ts
packages/swipe-cell/index.wxml

[new feature] SwipeCell: add new component swipe-cell

---

example/pages/checkbox/index.js
example/pages/checkbox/index.wxml
packages/checkbox/README.md

Checkbox: update docs

---

packages/steps/index.less
packages/steps/index.wxml

- [improvement] Steps: 优化样式使组件方便通过custom-class修改根节点属性
目前通过 custom-class 修改 padding 属性如设置 padding: 0 会导致最后一个 step 位置偏移

[improvement] Steps: 优化样式使组件方便通过custom-class修改根节点属性

---

packages/icon/index.less

[new feature] Icon: add new icon question2

---

packages/tree-select/index.less
packages/tree-select/index.wxml

[bugfix] TreeSelect: 修复与页面下拉刷新冲突

---

packages/cell/README.md
packages/cell/index.less
packages/cell/index.ts
packages/cell/index.wxml

[new feature] Cell: 增加 `arrow-direction` 属性

---

packages/slider/index.ts

[bug fix] Slider: 支持动态修改传入的value

---

packages/badge-group/index.ts
packages/common/utils.ts

[bugfix] Badge: active 属性在 mpvue 中不生效

---

example/pages/search/index.js
example/pages/search/index.wxml
packages/field/README.md
packages/field/index.ts
packages/search/README.md
packages/search/index.ts
packages/search/index.wxml

- Search、Field增加点击清除的Event事件：bind:clear

[improvement] Search&Field: add clear event.

---

packages/field/README.md
packages/field/index.ts
packages/field/index.wxml

[new feature] Field: 增加新属性 fixed

---

packages/dialog/README.md
packages/dialog/dialog.ts
packages/dialog/index.ts
packages/dialog/index.wxml

[new feature] Dialog: 增加新属性transition

---

packages/datetime-picker/index.ts

[bugfix] DatetimePicker: 修复动态设置type后报错

---

packages/collapse-item/index.wxml

[bugfix] Collapse: 修复箭头方向错误

---

example/pages/goods-action/index.wxml
example/pages/submit-bar/index.wxml
example/pages/tabbar/index.wxml
packages/action-sheet/README.md
packages/action-sheet/index.ts
packages/action-sheet/index.wxml
packages/common/style/var.less
packages/goods-action/README.md
packages/goods-action/index.less
packages/goods-action/index.ts
packages/goods-action/index.wxml
packages/mixins/basic.ts
packages/popup/README.md
packages/popup/index.less
packages/popup/index.ts
packages/popup/index.wxml
packages/submit-bar/README.md
packages/submit-bar/index.less
packages/submit-bar/index.ts
packages/submit-bar/index.wxml
packages/tabbar/README.md
packages/tabbar/index.less
packages/tabbar/index.ts
packages/tabbar/index.wxml

new feature: 适配iPhoneX

---

packages/field/README.md
packages/field/index.ts
packages/field/index.wxml

[new feature] Field: 增加新属性 showConfirmBar

---

packages/tab/README.md

修复 #1041 
- 完善Tab组件sticky属性的文档示例

docs(Tab): improve docs for sticky

---

packages/switch-cell/README.md
packages/switch-cell/index.ts
packages/switch-cell/index.wxml

[new feature] SwitchCell: add new props active-color、inactive-color

---

packages/action-sheet/index.wxml

[bugfix] Tabs：修复actions动态变化时，渲染后button被打散

[bugfix] ActionSheet：修复actions动态变化时，渲染后button被打散的问题

---

example/pages/stepper/index.wxml
example/pages/stepper/index.wxss
packages/stepper/index.less
packages/stepper/index.ts
packages/stepper/index.wxml

[bugfix] Stepper: 修复iPad下或修改input高度时输入框样式异常

---

example/pages/card/index.wxml
example/pages/card/index.wxss
packages/card/index.less
packages/card/index.ts
packages/card/index.wxml

[new feature] Card: update style

---

packages/collapse-item/index.ts

fix collapse height issue

---

example/pages/stepper/index.wxml

[improvement] Stepper: add padding to async example

[Doc] Stepper: add padding to async example

---

packages/goods-action-icon/index.less

fixed: https://github.com/youzan/vant-weapp/issues/1122

[bugfix] GoodsAction: GoodsAction info display incompletely

---

example/pages/tab/index.wxml
packages/tab/README.md
packages/tab/index.ts
packages/tab/index.wxml
packages/tabs/index.json
packages/tabs/index.less
packages/tabs/index.wxml

[new feature] Tab: 增加新属性 dot、info、title-style

---

example/pages/area/index.wxml
packages/area/index.ts
packages/datetime-picker/index.ts
packages/mixins/observer/behavior.ts
packages/picker-column/index.ts
packages/picker/index.ts

[bugfix] Area: 修复初始选中项错误

---

example/pages/field/index.js
example/pages/field/index.wxml
packages/field/index.ts

- blur 时检查value是否与输入框值相同，否则触发change

[bugfix] Field：手写键盘输入时未触发change事件

---

packages/area/index.ts
packages/picker/index.ts

[bugfix] Area: 修复getIndexes结果不符合预期

---

packages/search/index.wxml

[bugfix] Search: 修复readonly属性无效

---

packages/field/index.less

[bugfix] Field: 修复清除图标未居中

---

packages/card/index.less
packages/card/index.wxml

- 修复 centered 属性无效 #1243 
- 去除title、desc长度限制

[bugfix] Card: 修复centered属性无效，去除title、desc长度限制

---

packages/search/README.md

- 改动一
showAction->use-action-slot

[improvement]Search: 完善Search文档

---

packages/button/index.less
packages/button/index.ts
packages/button/index.wxml
packages/mixins/button.ts
packages/mixins/open-type.ts

- 增加新属性 ariaLabel
- 增加外部样式类 hover-class
- 增加launchapp事件

[new feature] Button:  增加新属性 ariaLabel、增加外部样式类 hover-class、增加launchapp事件

---

packages/dialog/README.md
packages/dialog/dialog.ts
packages/dialog/index.ts
packages/dialog/index.wxml
packages/mixins/button.ts

[new feature] Dialog: 支持openType相关参数

---

packages/notify/index.less

[improvement] Notify: support word break

---

example/pages/tab/index.js
example/pages/tab/index.wxml
example/pages/tab/index.wxss
packages/mixins/basic.ts
packages/tab/README.md
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml
types/wx.d.ts

支持 #1316 
- refactor sticky implementation
- improve performance
- add new slot left-nav & right-nav

[new feature] Tab: refactor component & add new slot

---

example/pages/transition/index.js
example/pages/transition/index.wxml
example/pages/transition/index.wxss
packages/mixins/transition.ts
packages/overlay/index.less
packages/overlay/index.ts
packages/overlay/index.wxml
packages/popup/README.md
packages/popup/index.less
packages/popup/index.ts
packages/popup/index.wxml
packages/transition/README.md
packages/transition/index.less
packages/transition/index.ts
packages/transition/index.wxml

- refactor with css transition
- add a bunch of external classes
- support custom enter & leave duration

[new feature] Transition: refactor with css transition

---

example/pages/field/index.wxml
packages/field/README.md
packages/field/index.ts
packages/field/index.wxml

[new feature] Field: add new prop size

---

packages/tab/index.wxml
packages/tabs/index.ts

[bugfix] Tab: offset-set not work、build class wrong

---

packages/area/index.ts

[bugfix] Area: incorrect initial index when set columns-num 2

---

packages/picker/README.md

[docs] Picker: advanced example incorrect

---

example/pages/tab/index.wxml
example/pages/tab/index.wxss
packages/tab/README.md
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml

[new feature] Tab: add new external class nav-class、tab-class、tab-active-class

---

packages/icon/index.less
packages/icon/index.wxml

[bugfix] Icon: info z-index higher than image

---

packages/swipe-cell/index.ts
packages/swipe-cell/index.wxml

[bugfix] SwipeCell: prevent page scroll

---

packages/datetime-picker/README.md

[docs] DatetimePicker: fix wrong example

---

packages/picker-column/index.ts

[bugfix] Picker: defaultIndex not work

---

packages/info/index.less
packages/info/index.wxml

[bugfix] Info: fix wrong style

---

packages/common/style/var.less
packages/stepper/index.less
packages/stepper/index.ts
packages/stepper/index.wxml

[new feature] Stepper: update style

---

example/pages/popup/index.wxml
packages/mixins/transition.ts
packages/popup/index.less
packages/popup/index.ts
packages/popup/index.wxml

[bugfix] Transition: behavior error when set duration zero

---

packages/goods-action-button/index.wxml
packages/goods-action-icon/index.ts
packages/goods-action-icon/index.wxml
packages/goods-action/README.md

[bugfix] GoodsAction: fix document error, fix disabled & loading not work

---

build/compiler.js
package.json
postcss.config.js
yarn.lock

- upgrade dependence
- use cssnano instead of clean-css

[build]: upgrade dependence & use cssnano instead of clean-css

---

packages/swipe-cell/index.wxml

[bugfix] SwipeCell: close event never emit

---

packages/slider/index.ts
packages/slider/index.wxml

[bugfix] Slider: fix click not work

---

build/compiler.js
package.json

[new feature]: compile es5 dist

---

README.md

- 修复 README 中 change log 链接错误的问题

[docs] README: fix change log url

---

packages/collapse-item/index.less
packages/collapse-item/index.ts
packages/collapse-item/index.wxml
packages/collapse/index.ts

[bugfix] Collapse: improve performance & optimize initial style set

---

packages/collapse/index.ts

[bugfix] Collapse: remove reference from children of collapse when collapse-item unlinked

---

example/pages/field/index.wxml
example/pages/field/index.wxss
packages/field/README.md
packages/field/index.less
packages/field/index.ts
packages/field/index.wxml

fix #1483
- add new slot right-icon
- add new prop right-icon
- add new external class right-icon-class
- implement placeholder with view in textarea mode

[improvement] Field: add right-icon & fix placeholder style problem

---

packages/notify/index.less
packages/notify/index.ts
packages/notify/index.wxml
packages/notify/notify.ts

[new feature] Notify: add new prop zIndex

---

example/pages/picker/index.wxml
packages/area/index.ts
packages/datetime-picker/index.ts
packages/picker-column/index.ts
packages/picker/README.md
packages/picker/index.ts
packages/picker/index.wxml
packages/picker/shared.ts

[new feature] Picker: add new prop default-index

---

packages/toast/README.md
packages/toast/index.ts
packages/toast/index.wxml
packages/toast/toast.ts

fix #1185
fix #1551
- add new option onClose
- add new slot

[new feature] Toast: add new option onClose & add new slot

---

packages/area/index.ts

[bugfix] Area: 修复同步设置areaList时不显示选项

---

example/pages/datetime-picker/index.js
example/pages/datetime-picker/index.wxml
packages/datetime-picker/README.md
packages/datetime-picker/index.ts
packages/datetime-picker/index.wxml
packages/picker-column/index.less

fix #1526
- add new prop formatter
- add new external classes

[new feature] DatetimePicker: add new prop formatter & add new external classes

---

example/pages/submit-bar/index.wxml
packages/submit-bar/README.md
packages/submit-bar/index.less
packages/submit-bar/index.ts
packages/submit-bar/index.wxml

- SubmitBar 组件 添加 tip-icon prop

[new feature] SubmitBar: add tip-icon prop

---

packages/notice-bar/README.md
packages/notice-bar/index.less
packages/notice-bar/index.wxml

修复 #1589 , 如果没有相关 issue, 请移除这行。

[new feature] NoticeBar: left-icon replact to Icon component

---

packages/checkbox/index.less

[bugfix] Checkbox: fix style error

---

example/pages/notice-bar/index.wxml
packages/notice-bar/index.less
packages/notice-bar/index.ts
packages/notice-bar/index.wxml

[new feature] NoticeBar: add new prop wrapable

---

packages/mixins/transition.ts

[bugfix] Transition: 修复leave阶段时节点不消失

---

example/pages/rate/index.js
example/pages/rate/index.wxml
packages/common/style/var.less
packages/rate/README.md
packages/rate/index.less
packages/rate/index.ts
packages/rate/index.wxml

[new feature] Rate: add new prop allow-half

---

packages/tabbar/README.md

[docs] Tabbar: 修复文档标题错误

---

packages/datetime-picker/index.ts

[bugfix] DatetimePicker: 修复wepy中组件初始化报错

---

example/pages/checkbox/index.js
example/pages/checkbox/index.wxml
example/pages/radio/index.js
example/pages/radio/index.wxml
example/pages/radio/index.wxss
packages/checkbox-group/index.ts
packages/checkbox/README.md
packages/checkbox/index.less
packages/checkbox/index.ts
packages/common/style/var.less
packages/radio-group/index.ts
packages/radio/README.md
packages/radio/index.less
packages/radio/index.ts
packages/radio/index.wxml

[new feature] Radio & Checkbox: 统一Radio与Checkbox的API

---

packages/submit-bar/index.json

[bugfix] SubmitBar: fix tip-icon not work

---

packages/radio/index.wxml

[bugfix] Radio: 修复未选中状态下checkedColor生效

---

packages/mixins/transition.ts
packages/popup/index.wxml

[bugfix] Transition: fix timing error

---

packages/progress/index.less
packages/progress/index.ts
packages/progress/index.wxml
packages/progress/index.wxs

[bugfix] Progress: refactor component

---

example/app.json
example/custom-tab-bar/index.js
example/custom-tab-bar/index.json
example/custom-tab-bar/index.wxml
example/pages/dashboard/index.js
example/pages/dashboard/index.wxml
example/pages/tabbar/index.js
example/pages/tabbar/index.wxml
example/pages/tabbar1/index.js
example/pages/tabbar1/index.json
example/pages/tabbar1/index.wxml
example/pages/tabbar1/index.wxss
packages/tabbar-item/index.ts
packages/tabbar-item/index.wxml
packages/tabbar/README.md
packages/tabbar/index.ts

fix #1625
- 重构组件，优化性能
- 新增 inactiveColor、name 属性
- 完善文档，增加小程序自定义tab-bar示例

[new feature] TabBar: improve performance & add new props & improve doc

---

packages/datetime-picker/index.ts

[bugfix] DatetimePicker: 修复动态更新minDate时未更新数据

---

packages/area/README.md

- update the url
- rename from `Area.json` to `area.js`

[Doc] Area: update the link of Area.json

---

packages/swipe-cell/index.ts

[improvement] Swipe-cell vertical scrolling in iOS

---

packages/field/index.less

[bugfix] field: unify textarea placeholder style with input

---

packages/switch-cell/README.md
packages/switch-cell/index.ts
packages/switch-cell/index.wxml

[new feature] SwitchCell: add new prop & slot of cell

---

packages/mixins/transition.ts
packages/popup/index.ts

[improvement] Transition: remove classNames from data

---

packages/radio/index.ts
packages/radio/index.wxml

[bugfix] Radio: fix label-position not work

---

packages/dialog/README.md
packages/dialog/dialog.ts
packages/dialog/index.ts
packages/dialog/index.wxml

[new feature] Dialog: add new prop custom-style

---

packages/picker-column/index.wxml
packages/picker-column/index.wxs

[bugfix] Picker: show [object object] while text is 0

---

packages/field/index.less

https://github.com/youzan/vant-weapp/issues/1725

[bugfix] Field: error prop not work

---

packages/button/README.md

https://github.com/youzan/vant-weapp/issues/1725

[Doc] Button: add click event tips

---

packages/notify/notify.ts

https://github.com/youzan/vant-weapp/issues/1803

[improvement] Notify: optimize set data

---

packages/stepper/README.md
packages/stepper/index.ts
packages/stepper/index.wxml

https://github.com/youzan/vant-weapp/issues/1812

[new feature] Stepper: add show-plus & show-minus prop

---

dist/wxs/utils.wxs

- wxs/utils.wxs增加代码：url.indexOf(".") === 0 || url.indexOf("/") === 0 || ，以 “.” , "/", "../" 开头的本地路径可以被读取

[new feature]Icon：icon name添加识别本地图片路径的功能

---

packages/mixins/transition.ts

改动一   const currentDuration = isObj(duration) ? <del>duration.leave</del>  duration.enter : duration;

[bugfix]  Transition:动画enter的时候应该时候duration应该是duration.enter

---

example/pages/tree-select/index.js
example/pages/tree-select/index.wxml
packages/tree-select/README.md
packages/tree-select/index.wxml
packages/tree-select/index.wxs

[bugfix] TreeSelect: fix error when type of activeId is string or number

---

packages/common/utils.ts
packages/field/README.md
packages/field/index.less
packages/field/index.ts
packages/field/index.wxml

fix #1849 
fix #1779
fix #1735
fix #1906

[bugfix] Field: never change value in blur event & handle style difference between iOS and Android

---

example/pages/radio/index.wxml
packages/radio/README.md

[bugfix] Radio: fix doc error

---

example/pages/button/index.wxml
packages/button/README.md
packages/button/index.ts
packages/button/index.wxml

[new feature] Button 组件新增 `loading-type` prop

feat(Button): add loading-type prop

---

example/pages/datetime-picker/index.js
example/pages/datetime-picker/index.wxml
packages/datetime-picker/README.md
packages/datetime-picker/index.ts

[new feature] DatetimePicker 新增filter prop

feat(DatetimePicker): add filter prop

---

example/pages/steps/index.js
example/pages/steps/index.wxml
packages/steps/README.md
packages/steps/index.ts
packages/steps/index.wxml

[new feature] Steps: 增加 `active-icon` prop

feat(Steps): add active-icon prop

---

example/pages/rate/index.wxml
packages/common/utils.ts
packages/rate/README.md
packages/rate/index.ts
packages/rate/index.wxml

[new feature] Rate: 增加 `gutter` prop

feat(Rate): add gutter prop

---

packages/slider/README.md
packages/slider/index.ts

[new feature] Slider: `bar-height` prop 支持 number 格式

feat(Slider): bar-height prop support number

---

example/pages/rate/index.wxml
packages/rate/README.md
packages/rate/index.ts
packages/rate/index.wxml

[new feature] Rate:  `size` prop 支持 string 格式

feat(Rate): size prop support string

---

example/pages/steps/index.wxml
packages/steps/README.md
packages/steps/index.ts
packages/steps/index.wxml

[new feature] Steps: 增加 `inactive-icon` prop

feat(Steps): add inactive-icon prop

---

example/pages/slider/index.wxml
packages/slider/README.md
packages/slider/index.ts

feat(Slider): min & max support arbitrary value

feat(Slider): min & max support arbitrary value

---

packages/icon/README.md
packages/icon/index.ts
packages/icon/index.wxml

- feat(Icon): size prop support number type

feat(Icon): size prop support number type

---

example/app.json
example/config.js
example/pages/overlay/index.js
example/pages/overlay/index.json
example/pages/overlay/index.wxml
example/pages/overlay/index.wxss
packages/overlay/README.md
packages/overlay/index.ts

feat(Overlay): add component overlay

[new feature]: 新增组件overlay

---

packages/action-sheet/README.md
packages/action-sheet/index.ts
packages/action-sheet/index.wxml

feat(ActionSheet): add click-overlay
上拉菜单新增事件：click-overlay 点击遮罩层时触发

feat(ActionSheet): add click-overlay

---

example/pages/action-sheet/index.js
example/pages/action-sheet/index.wxml
example/pages/circle/index.js
packages/action-sheet/README.md

docs: fix ActionSheet example doc

---

packages/checkbox/README.md
packages/checkbox/index.less
packages/checkbox/index.ts
packages/checkbox/index.wxml

feat(Checkbox): add icon-size prop

feat(Checkbox): add icon-size prop

---

example/pages/goods-action/index.wxml
packages/goods-action-button/index.ts
packages/goods-action-button/index.wxml
packages/goods-action/README.md

feat(GoodsActionButton): add color prop

feat(GoodsActionButton): add color prop

---

package.json
yarn.lock

https://github.com/youzan/vant-weapp/issues/1936

feat(Icon): add down、wap-home icon

---

example/pages/rate/index.wxml
packages/rate/README.md
packages/rate/index.ts

feat(Rate): add touchable prop

feat(Rate): add touchable prop

---

example/pages/progress/index.wxml
packages/progress/README.md
packages/progress/index.ts
packages/progress/index.wxml

feat(Progress): add stroke-width prop

feat(Progress): add stroke-width prop

---

packages/progress/README.md

docs(Progress): add stroke-width prop

docs(Progress): add stroke-width prop

---

example/pages/notice-bar/index.wxml
packages/notice-bar/README.md
packages/notice-bar/index.wxml

feat(NoticeBar): add left/right-icon slot

feat(NoticeBar): 添加NoticeBar左右插槽/补充文档

---

example/pages/notify/index.js
example/pages/notify/index.wxml
packages/common/style/var.less
packages/notify/README.md
packages/notify/index.less
packages/notify/index.ts
packages/notify/index.wxml
packages/notify/notify.ts

- feat(Notify): 增加 primary/success/danger/warning type
- feat(Notify): 增加 onOpened onClose onClick 回调

feat(Notify): 增加 type 和 onOpened onClose onClick 回调

---

example/pages/dialog/index.js
example/pages/dialog/index.wxml
packages/button/README.md
packages/button/index.ts
packages/button/index.wxml
packages/common/color.ts
packages/dialog/README.md
packages/dialog/index.less
packages/dialog/index.ts
packages/dialog/index.wxml

feat(Dialog): 增加 title插槽 和 confirm-button-color  cancelfirm-button-color 属性
feat(Button): 增加 custom-style 属性

feat(Dialog): 增加 title插槽 和 confirm-button-color  cancelfirm-button-color 属性

---

example/app.json
example/config.js
example/pages/divider/index.js
example/pages/divider/index.json
example/pages/divider/index.wxml
example/pages/divider/index.wxss
packages/common/style/var.less
packages/divider/README.md
packages/divider/index.json
packages/divider/index.less
packages/divider/index.ts
packages/divider/index.wxml

 feat(Divider): add divider

---

packages/swipe-cell/README.md
packages/swipe-cell/index.ts

feat(SwipeCell): add name prop

---

packages/common/style/var.less
packages/icon/README.md
packages/icon/index.ts
packages/icon/index.wxml
packages/info/index.less
packages/info/index.ts
packages/info/index.wxml

feat(Icon): add dot prop

---

example/pages/tab/index.js
example/pages/tab/index.wxml
packages/common/utils.ts
packages/tab/README.md
packages/tab/index.ts
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml

1. add name prop
2. add line-height prop
3. line-width support string type
4. replace dot with van-info api

feat(Tab): improve the prop of Tab

---

packages/swipe-cell/index.ts

feat(SwipeCell): support mutual exclusion

---

packages/action-sheet/README.md

https://github.com/youzan/vant-weapp/issues/2130

docs(ActionSheet): fix typo

---

packages/radio/README.md

docs(Radio): setData params error

docs(Radio): setData params error

---

packages/tabs/index.ts

fix(Tabs): some error when component init

---

packages/nav-bar/index.less
packages/nav-bar/index.ts
packages/nav-bar/index.wxml

fix(NavBar): fix safeAreaInsetTop not work in android device

---

example/pages/transition/index.js
example/pages/transition/index.wxml
packages/mixins/transition.ts
packages/popup/README.md
packages/transition/README.md

BREAKING CHANGE: drop transitionend event
fix #2071

feat(Transition): add new lifecycle events & drop transitionend event

---

example/pages/area/index.wxml
packages/area/README.md
packages/area/index.ts

feat(Area): add columns placeholder

feat(Area): add columns placeholder

---

packages/steps/index.less
packages/steps/index.wxml

https://github.com/youzan/vant-weapp/issues/2165

fix(Steps): incorrect style when use inactive-icon prop

---

packages/action-sheet/index.less
packages/common/style/var.less
packages/switch/index.less

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

feat(ActionSheet): action-sheet组件样式变量化

---

packages/card/index.less
packages/common/style/var.less

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

feat(Card): card组件样式变量化

---

packages/button/index.less
packages/common/style/var.less

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

Button css

---

packages/area/index.ts

area 配置 Columns placeholder  选项保留undefined 返回值

fix(Area): Columns placeholder return value keep undefined

---

packages/count-down/index.ts

fix(CountDown): destroy timer when Component destroyed (#2199)

fix(CountDown): destroy timer when Component destroyed (#2199)

---

packages/datetime-picker/README.md
packages/datetime-picker/index.ts

#2168 
fix(DatetimePicker): Selector error when setting filter option

fix(DatetimePicker): Selector error when setting filter option

---

packages/cell/index.less
packages/common/style/var.less
packages/field/index.less

feat(Field): Field 组件样式变量化
feat(Card): Card 组件样式变量化
feat(Cell):  Cell 组件样式变量化

feat: Field, Card, Cell 组件样式变量化

---

packages/common/style/var.less
packages/panel/index.less

feat(Panel): Panel组件样式调整

---

packages/grid-item/index.less

feat(GridItem): GridItem 组件样式调整

feat(GridItem): GridItem 组件样式调整

---

packages/dropdown-item/index.less
packages/dropdown-menu/index.less

feat(DropDowm): DropDowm组件样式调整

feat(DropdownMenu): DropdownMenu 组件样式调整

---

packages/common/style/var.less
packages/popup/index.less

feat(Popup): Popup 组件样式调整

---

packages/common/style/var.less
packages/dialog/index.less

feat(Dialog): Dialog 组件样式调整

---

example/pages/tag/index.js
example/pages/tag/index.wxml
packages/common/style/var.less
packages/tabbar-item/index.less
packages/tabbar-item/index.wxml
packages/tabbar/index.less
packages/tag/index.less
packages/tag/index.ts
packages/tag/index.wxml

Tabbar
- support css variables
Tag
- support css variables
- add new prop closeable

feat(Tabbar & Tag): support css variables

---

packages/common/style/var.less
packages/notice-bar/index.less

feat(NoticeBar): NoticeBar组件样式调整

feat(NoticeBar): NoticeBar组件样式调整

---

packages/common/style/var.less
packages/goods-action-button/index.less
packages/goods-action-icon/index.less
packages/goods-action/index.less

feat(GoodsAction): goodsAction 组件样式调整

feat(GoodsAction): goodsAction 组件样式调整

---

packages/common/style/var.less
packages/nav-bar/index.less

feat(NavBar): NavBar组件样式调整

---

packages/common/style/var.less
packages/picker-column/index.less
packages/picker/index.less

feat(Picker): Picker组件样式调整

---

example/app.json
example/config.js
example/pages/skeleton/index.js
example/pages/skeleton/index.json
example/pages/skeleton/index.wxml
example/pages/skeleton/index.wxss
packages/common/style/var.less
packages/skeleton/README.md
packages/skeleton/index.json
packages/skeleton/index.less
packages/skeleton/index.ts
packages/skeleton/index.wxml

feat: add feature skeleton

---

packages/common/style/var.less
packages/progress/index.less

feat(Progress): Progress 组件样式调整

feat(Progress): Progress 组件样式调整

---

packages/submit-bar/index.less

feat(SubmitBar): SubmitBar组件样式调整

feat(SubmitBar): SubmitBar组件样式调整

---

packages/common/style/var.less
packages/loading/index.less
packages/toast/index.less

feat(Toast, Loading): Toast, Loading 组件样式调整

feat(Toast, Loading): Toast, Loading 组件样式调整

---

example/pages/tab/index.js
example/pages/tab/index.wxml
example/pages/tab/index.wxss
packages/common/style/var.less
packages/sticky/index.less
packages/sticky/index.ts
packages/sticky/index.wxml
packages/tab/index.ts
packages/tabs/index.json
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml

fix #2253 #2122 
+ support css variables

refactor(Tab): refactor component with Sticky

---

packages/area/index.ts

fix(Area): fix change event emit wrong values

---

dist/dropdown-menu/index.js

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

fix:annotation error

---

example/pages/uploader/index.wxml
packages/uploader/index.ts

fix(Uploader): fix multiple not work

---

packages/icon/index.less
packages/nav-bar/index.less

fix(NavBar): fix icon style error

---

dist/rate/index.wxml
example/pages/rate/index.wxml
lib/rate/index.wxml
packages/rate/index.wxml

fix(rate): use size attribute (#2325)

---

example/pages/sticky/index.js
example/pages/sticky/index.wxml
example/pages/tab/index.js
packages/sticky/README.md
packages/sticky/index.ts
packages/sticky/index.wxml
packages/tab/README.md
packages/tab/index.less
packages/tab/index.ts
packages/tab/index.wxml
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml

Tab
- add new prop lazyRender
- improve performace
Sticky
- add new prop container

feat(Tab): add new prop lazyRender & improve performance

---

packages/tab/index.ts
packages/tab/index.wxml
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml
packages/tabs/index.wxs

feat(Tab): add new prop ellipsis & improve performance

---

packages/uploader/index.wxml

fix(uploader): preview-size repeat px

---

packages/skeleton/index.wxml

fix(Skeleton): fix prop row not work error

---

packages/tab/index.ts
packages/tab/index.wxml
packages/tabs/index.less
packages/tabs/index.ts
packages/tabs/index.wxml

fix(Tab): fix getComputedName of undefined error

---

packages/notify/index.less
packages/notify/index.ts
packages/notify/notify.ts

fix(Notify): safe-area not work in android

---

packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/index.ts

fix(Grid): gutter not work correct with square

---

example/pages/tab/index.wxml
packages/tabs/index.ts

fix(Tab): fix prop active not work in init

---

packages/image/index.ts
packages/image/index.wxml

fix(Image): support set width & height dynamic

---

example/app.js
example/pages/area/index.js
packages/area/README.md

feat: 将省市区数据存储在云开发数据库中

---

packages/area/README.md

docs(Area): fix demo problem

---

packages/mixins/touch.ts
packages/swipe-cell/README.md
packages/swipe-cell/index.ts
packages/swipe-cell/index.wxml

feat(SwipeCell): add new event open & stop catch touchend

---

example/pages/uploader/index.js
example/pages/uploader/index.wxml
packages/uploader/README.md

feat:Uploader加入上传云存储示例

---

packages/dropdown-item/index.ts
packages/dropdown-menu/index.ts
packages/dropdown-menu/index.wxml
packages/dropdown-menu/index.wxs

fix(DropdownMenu): support set props dynamic & improve performance

---

packages/image/index.wxml

fix(Image): remove webp

---

packages/circle/README.md

docs(Circle): adjust wrong readme 

---

example/pages/overlay/index.js
example/pages/overlay/index.wxml
example/pages/overlay/index.wxss
packages/overlay/README.md
packages/overlay/index.wxml

feat(Overlay): add default slot

---

packages/goods-action/README.md

docs(GoodsAction): fix demo problem
修复文档中自定义按钮颜色示例代码错误
fix #2452

docs(GoodsAction): fix demo problem

---

packages/tree-select/index.wxml

fix(TreeSelect): support set mainActiveIndex dynamic

---

packages/sidebar/README.md

docs(Sidebar): rename prop active to activeKey

---

packages/sidebar/index.ts

fix(Sidebar): fix emit wrong index in click event after render new sidebar-item list

---

packages/stepper/README.md
packages/stepper/index.ts

feat(Stepper): add disablePlus & disableMinus props

feat(Stepper): add disablePlus & disableMinus props

---

packages/notify/README.md
packages/notify/notify.ts

https://github.com/youzan/vant/issues/5201

feat(Notify): add clear method

---

example/pages/field/index.js
example/pages/field/index.wxml
packages/field/README.md

docs(Field): add input-align example [#2496](https://github.com/youzan/vant-weapp/issues/2496)
添加说明

docs(Field): add input-align example  #2496

---

example/pages/notice-bar/index.js
example/pages/notice-bar/index.wxml
packages/notice-bar/README.md
packages/notice-bar/index.ts

添加notice-bar 组件speed属性 示例 #2492

docs(notice-bar): add notice-bar example

---

example/pages/swipe-cell/index.js
example/pages/swipe-cell/index.wxml
packages/swipe-cell/README.md

docs(swipe-cell): add swipecell example

---

packages/steps/README.md
packages/steps/index.ts
packages/steps/index.wxml

feat:  Steps 组件支持 inactive-color 新特性
fix #2321

feat(Steps):  add inactive-color feature

---

packages/uploader/README.md
packages/uploader/index.less
packages/uploader/index.ts
packages/uploader/index.wxml

fix(Uploader): remove use-slot & catch upload error & fix prop capture not work

---

packages/swipe-cell/README.md

#2547 
docs(SwipeCell): add async-close instruction

docs(SwipeCell): add async-close instruction

---

example/pages/notify/index.js
example/pages/notify/index.wxml
packages/notify/index.ts
packages/notify/index.wxml
packages/notify/notify.ts

fix(Notify): fix safeAreaInsetTop not work

---

example/pages/button/index.wxml
example/pages/cell/index.wxml
example/pages/checkbox/index.js
example/pages/checkbox/index.wxml
example/pages/radio/index.js
example/pages/radio/index.wxml
packages/button/README.md
packages/cell/README.md
packages/checkbox/README.md
packages/checkbox/index.less
packages/radio/README.md
packages/radio/index.less
packages/radio/index.wxml

- docs(Button): 添加块级元素事例
- docs(Cell): 添加多行文本垂直居中事例
- docs(Checkbox): 添加自定义图标大小，禁用文本点击事例
- docs(Radio): 添加自定义图标大小，自定义形状，禁用文本点击事例
- fix(Checkbox): 图标与内容垂直居中
- fix(Radio): 自定义图标显示正确的大小，图标与内容垂直居中

docs(Button/Cell/Checkbox/Radio):  update some examples

---

packages/tag/index.json

fix(Tag): add component dependence van-icon

---

packages/field/index.ts
packages/field/index.wxml

fix(Field): catch touchstart event to fix #1430

---

packages/index-bar/index.ts

fix(IndexBar): fix error in click event

---

packages/tab/index.less

perf(Tab): improve scrolling

---

packages/swipe-cell/index.ts

feat(SwipeCell): support dynamic set width  #2571

feat(SwipeCell): support dynamic set width

---

docs/markdown/quickstart.md

feat(README): supplement README.md

docs(README):  add vant-weapp demo link

---

packages/skeleton/index.ts
packages/skeleton/index.wxml

feat(Skeleton): add new external class row-class & avatar-class & title-class

---

packages/datetime-picker/README.md

docs(DatetimePicker)：fix DatetimePicker docs show-toolbar
示例：

docs(DatetimePicker): correct defaults

---

README.md

fix(readme): fix link to miniprogram quickstart

---

packages/nav-bar/index.less

fix(NavBar): fix icon and text dislocation
fix: #2627

fix(NavBar): fix icon and text dislocation

---

packages/toast/README.md

docs(Toast): add OnClose function demo

docs(Toast): add OnClose function demo

---

example/pages/button/index.wxml
example/pages/cell/index.wxml
packages/button/README.md
packages/cell/README.md

- docs(Button) 更新块级元素 README 和示例
- docs(Cell) 更新垂直元素 README 和示例

docs(Button/Cell): keep up with vant

---

packages/dropdown-item/index.wxml

fix(DropdownItem): fix wx:key wran #2669

fix(DropdownItem): fix wx:key wran

---

packages/icon/README.md

docs(Icon): introduce failed to load font in wechat devtool

---

packages/index-bar/README.md

fix(IndexBar): fix README.md demo's path
fix #2688

fix(IndexBar): fix README.md demo's path

---

packages/sticky/index.ts
packages/sticky/index.wxml
packages/sticky/index.wxs

fix(Sticky): avoid sticky not fixed when scroll slow & improve performance

---

example/pages/search/index.wxml
packages/search/README.md

feat(Search):  add Search demo

docs(Search):  add Search demo

---

packages/tree-select/README.md

docs(TreeSelect): fix readme error

---

packages/radio/index.ts

fix(Radio): fix disabled not work

---

packages/tabs/index.ts
packages/tabs/index.wxml
packages/tabs/index.wxs

fix(Tab): support set animated dynamic

---

packages/common/style/var.less
packages/uploader/index.less
packages/uploader/index.wxml

feat(Uploader): add uploader component  disabled style
fix #2716

feat(Uploader): add uploader component  disabled style

---

docs/markdown/quickstart.md

docs(quickstart): fix usingComponents path error

---

example/pages/action-sheet/index.js
example/pages/action-sheet/index.wxml
packages/action-sheet/README.md
packages/action-sheet/index.ts
packages/action-sheet/index.wxml

fix(ActionSheet): support more options

---

docs/markdown/quickstart.md

docs(quickstart): optimize quickstart

---

README.md

docs(README): update package name

---

packages/checkbox-group/index.ts
packages/checkbox/index.ts
packages/checkbox/index.wxml
packages/checkbox/index.wxs

fix(Checkbox): support set disabled dynamic

---

packages/button/index.wxml

fix(Button): add loading color when plain is true

fix(Button): add loading color when plain is true

---

example/app.json
example/components/demo-home-nav/index.json
example/components/demo-home-nav/index.wxss
example/components/demo-home/index.json
example/pages/card/index.js
example/pages/dashboard/index.json
example/pages/goods-action/index.wxml
example/pages/goods-action/index.wxss
example/pages/grid/index.js
example/pages/grid/index.wxml
example/pages/submit-bar/index.wxml
example/pages/submit-bar/index.wxss
example/pages/tab/index.js
example/pages/tab/index.wxml
example/pages/tabbar/index.wxml
example/pages/tabbar/index.wxss

1. 规范一些写法
2. 调整一些样式名
正常对展示结果无影响

chore: change some demo code

---

packages/button/index.ts
packages/button/index.wxml
packages/col/index.ts
packages/col/index.wxml
packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/index.ts
packages/grid/index.wxml
packages/image/index.ts
packages/image/index.wxml
packages/loading/index.ts
packages/loading/index.wxml
packages/notify/index.ts
packages/row/index.ts
packages/row/index.wxml

1. 处理data中style字段名为其他字段名
2. 处理wx:for循环使用数组
3. 某些字段增加初始值定义

chore: change data name

---

packages/tabs/index.ts

Tabs 的 disabled事件传递的内容由原先的选中项信息改为点击项信息

fix(Tabs): fix disabled event data

---

packages/checkbox-group/index.ts
packages/checkbox/index.ts
packages/col/index.ts
packages/collapse-item/index.ts
packages/collapse/index.ts
packages/common/component.ts
packages/definitions/index.ts
packages/dropdown-item/index.ts
packages/dropdown-menu/index.ts
packages/goods-action-button/index.ts
packages/goods-action/index.ts
packages/grid-item/index.ts
packages/grid/index.ts
packages/index-anchor/index.ts
packages/index-bar/index.ts
packages/radio-group/index.ts
packages/radio/index.ts
packages/row/index.ts
packages/sidebar-item/index.ts
packages/sidebar/index.ts
packages/tab/index.ts
packages/tabbar-item/index.ts
packages/tabbar/index.ts
packages/tabs/index.ts

refactor: refactor relation

---

packages/checkbox/README.md
packages/radio/README.md

docs(Radio): fix label-disabled error

---

packages/dropdown-item/index.ts

fix(DropdownItem): emit close while change item

---

example/pages/button/index.wxml
example/pages/image/index.wxml
example/pages/progress/index.wxml
example/pages/progress/index.wxss
example/pages/rate/index.wxml
example/pages/rate/index.wxss
example/pages/tab/index.wxml
example/pages/tab/index.wxss
packages/grid/index.ts
packages/rate/index.ts
packages/rate/index.wxml
packages/skeleton/index.ts
packages/skeleton/index.wxml
packages/tabs/index.ts

1. 删除未定义的组件
2. 调整部分样式名字
3. wx:for改使用数组形式
4. 调整Tabs初始化时机，正常无影响
5. 处理之前漏删除的东西

chore: change some style

---

packages/card/README.md
packages/card/index.ts
packages/card/index.wxml

feat(Card): add slots attrs

---

packages/radio/index.ts

fix(Radio): adjust name type to any

---

example/project.config.json
packages/dropdown-item/index.ts
packages/dropdown-item/index.wxml
packages/dropdown-menu/README.md
packages/mixins/transition.ts

feat(DropdownItem): add new event open close opend closed & new prop popup-style

---

packages/goods-action-button/index.less

fix(GoodsActionButton): fix style error in single action button

---

packages/picker/index.less
packages/picker/index.wxml
packages/picker/toolbar.wxml

fix(Picker): add mask

---

packages/sticky/index.ts
packages/tabs/index.ts

fix(Tab): set container when change active

---

packages/cell/index.less
packages/common/style/var.less

feat(Cell): improve cell value style in large size

feat(Cell): improve cell value style in large size

---

dist/picker/index.wxml
lib/picker/index.wxml
packages/picker/index.wxml

fix bug: add missing .wxml while importing template

---

packages/common/style/var.less
packages/field/README.md
packages/field/index.less
packages/field/index.ts
packages/field/index.wxml
packages/field/index.wxs

feat(Field): add new prop showWordLimit & support max/min height & add new css variables

---

example/pages/uploader/index.wxml
packages/uploader/README.md
packages/uploader/index.ts
packages/uploader/index.wxml

feat(Button): add show-upload prop
fix #2865

feat(Uploader): make upload botton selectable

---

packages/uploader/README.md
packages/uploader/index.ts
packages/uploader/index.wxml

feat(Uploader): add upload-icon props
上传按钮自定义

feat(Uploader): add upload-icon props

---

example/pages/sidebar/index.wxml
example/pages/sidebar/index.wxss
packages/sidebar-item/index.wxml
packages/sidebar/README.md

feat(SideBar): add title slot
fix #2829

feat(SideBar): title slot

---

packages/button/index.ts
packages/button/index.wxml

fix(Button): disabled button does not emit event handler
fix #2845

fix(Button): disabled button does not emit event handler

---

packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/README.md
packages/grid/index.wxml

feat(Grid): add new external class custom-class content-class icon-class text-class

---

packages/mixins/button.ts

fix(Button): remove default lang

---

example/pages/uploader/index.js
packages/common/style/var.less
packages/uploader/index.less
packages/uploader/index.ts
packages/uploader/index.wxml
packages/uploader/shared.ts
packages/uploader/utils.ts

perf(Uploader): update style & adjust event order

---

packages/nav-bar/README.md
packages/nav-bar/index.ts
packages/nav-bar/index.wxml

feat(NavBar): add new prop fill

---

packages/calendar/README.md

docs: fix method name conflicts with lifecycle

---

example/pages/uploader/index.js
example/pages/uploader/index.wxml
packages/common/style/var.less
packages/uploader/README.md
packages/uploader/index.json
packages/uploader/index.less
packages/uploader/index.wxml

feat(Uploader): add Uploader status display
fix: #2915

feat(Uploader): add Uploader status display

---

example/pages/sidebar/index.js
example/pages/sidebar/index.wxml
example/pages/sidebar/index.wxss
packages/sidebar/README.md

docs(Sidebar): adjust doc & example code

---

packages/tabs/index.wxml
packages/tabs/index.wxs

fix(Tab): fix Card Type Color custome
fix: #2914

fix(Tab): fix Card Type Color custome

---

packages/mixins/page-scroll.ts
packages/sticky/index.ts
packages/sticky/index.wxml
packages/sticky/index.wxs

refactor(Sticky): refactor component with page scroll

---

packages/calendar/index.wxs

fix(Calendar): fix wxs error on init  when showConfirm is true

---

packages/index-bar/README.md

chore(IndexBar): fix typo

---

packages/calendar/README.md

docs(Calendar): fix doc error

---

packages/skeleton/README.md

docs(Skeleton): fix doc error

---

packages/field/index.ts

fix(Field): support model value

---

packages/index-anchor/index.ts
packages/index-bar/README.md
packages/index-bar/index.ts

fix(IndexBar): remove prop scrollTop

---

packages/uploader/utils.ts

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

修改上传组件isImageUrl判断,有些七牛返回来的后缀的大写，加以判断

---

packages/action-sheet/README.md

docs: fix typo in action-sheet

docs: fix typo in action-sheet

---

packages/field/index.wxs

fix(Field): fix max-height not work

---

packages/field/index.ts

fix(Field): avoid setting showClear to undefined

---

packages/notify/README.md
packages/notify/index.ts
packages/notify/index.wxml
packages/notify/notify.ts

feat(Notify): add new prop top

---

packages/calendar/index.ts
packages/calendar/index.wxml
packages/calendar/utils.ts

perf(Calendar): auto selected to max range

---

packages/common/style/var.less
packages/goods-action-button/index.less

feat(GoodsActionButton): add new css variable goods-action-line-height

---

packages/field/index.wxs

fix(Field): avoid wxs error when set autosize

---

package.json
packages/uploader/README.md
packages/uploader/utils.ts
yarn.lock

feat(Uploader): prop accept add new value media

---

packages/dialog/index.wxml

fix(dialog): remove blank before title

---

packages/action-sheet/README.md

docs(actionsheet): fix doc error

---

.prettierrc
packages/uploader/index.ts
packages/uploader/index.wxml

fix(uploader): emit click-preview for all file type

---

packages/tabs/index.less

fix(tab): hide scrollbar

---

packages/button/index.wxml

fix(button): set open-type to null when disabled

---

packages/common/utils.ts
tsconfig.json

build(tsconfig): skipLibCheck to avoid dependecies error

---

packages/mixins/page-scroll.ts
packages/tabs/index.ts

fix(Sticky): pageScroll bind page

fix(Sticky): pageScroll bind page

---

packages/submit-bar/index.less
packages/submit-bar/index.wxml

refactor(submit-bar): implement safe-area-inset-bottom with another view

---

example/pages/sticky/index.js
example/pages/sticky/index.wxml
example/project.config.json
packages/mixins/page-scroll.ts
packages/sticky/README.md
packages/sticky/index.ts

feat(sticky): add new prop scroll-top

---

packages/common/README.md
packages/common/index.less
packages/common/style/normalize.less

https://github.com/youzan/vant-weapp/issues/3131

fix: page selector warning

---

packages/nav-bar/README.md
packages/nav-bar/index.ts
packages/nav-bar/index.wxml

feat(NavBar): support custom-style

---

packages/common/style/var.less

feat: change_field_placeholder_color

feat(Field): change placeholder color

---

example/pages/goods-action/index.wxml
packages/goods-action-button/index.ts
packages/goods-action/index.ts

fix(goods-action-button): rerender style after link change

---

packages/button/README.md

docs(button): update disable doc

---

packages/tab/README.md

docs(Tab): add use with popup doc

---

example/pages/collapse/index.js
example/pages/collapse/index.wxml
packages/collapse/README.md
packages/collapse/index.ts

feat(Collapse): add close open event
fix: #3142

feat(Collapse): add close open event

---

packages/common/style/var.less
packages/tag/index.less

fix(tag): fix wrong css variable name

---

example/pages/grid/index.wxml
packages/grid-item/index.less
packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/index.ts

feat(grid): add new prop direction

---

packages/button/README.md
packages/button/index.ts
packages/button/index.wxml

feat(button): add new prop form-type

---

packages/tag/README.md

docs(tag): add prop closable doc

---

example/pages/circle/index.wxml
package.json
packages/circle/README.md
packages/circle/canvas.ts
packages/circle/index.ts
packages/circle/index.wxml
yarn.lock

fix(circle): fix type not work

---

packages/uploader/index.wxml

fix(uploader): avoid emit click-preview event in delete event

---

example/pages/grid/index.wxml
packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/README.md
packages/grid/index.ts

feat(grid): add new prop icon-size & badge

---

packages/grid-item/index.ts

fix(Grid): fix square item gutter bug

fix(Grid): fix square item gutter bug

---

example/pages/nav-bar/index.wxml
example/project.config.json
packages/nav-bar/index.less
packages/nav-bar/index.ts
packages/nav-bar/index.wxml

fix(nav-bar): fix style error with no left-text

---

packages/circle/index.ts

fix(circle): can not set value dynamic

---

packages/uploader/index.less
packages/uploader/index.wxml

perf(uploader): expand delete area

---

packages/calendar/index.ts

fix(calendar): fix default-date not work in multiple mode

---

packages/grid/README.md

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

Update Grid direction README 

---

packages/grid-item/index.less

fix(grid): add margin-top for text with icon

---

packages/field/index.ts

fix(field): always set value after input

---

packages/tabbar/index.less

fix(tabbar): fix style error in iphonese

---

example/pages/steps/index.js
example/pages/steps/index.wxml
packages/steps/README.md
packages/steps/index.wxml

feat(steps): add new steps properties inactiveIcon & activeIcon

---

README.md
docs/markdown/intro.md

https://github.com/youzan/vant-weapp/issues/3324

docs: fix job link

---

packages/dialog/dialog.ts
packages/popup/index.ts

fix(dialog): show dialog after class ready

---

packages/nav-bar/README.md
packages/nav-bar/index.wxml

refactor(nav-bar): move customStyle to root view

---

packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/README.md

feat(GridItem): add icon-color prop

---

example/pages/notice-bar/index.js
example/pages/notice-bar/index.wxml
example/pages/notice-bar/index.wxss
packages/notice-bar/README.md
packages/notice-bar/index.ts
packages/notice-bar/index.wxml

feat(notice-bar): add new prop background & add new event close

---

packages/collapse-item/index.less
packages/collapse-item/index.ts
packages/collapse-item/index.wxml

fix(collapse): refactor with animation to improve performance

---

packages/field/README.md

docs(field): add example for two way binding

---

packages/slider/index.ts

fix(slider): avoid emit drag on click

---

packages/calendar/README.md

docs(calendar): add doc for min-date & max-date

---

example/project.config.json
packages/area/index.ts

fix(area): fix setValues error

---

packages/empty/README.md

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

Update Empty guide

---

example/project.config.json
packages/tree-select/README.md

docs(tree-select): add doc for height

---

packages/calendar/index.json

fix(calendar): add toast in json

---

packages/tabs/index.ts

fix(tab): avoid swipe to disabled tab

---

packages/common/utils.ts
packages/mixins/transition.ts

fix #3133, fix #3120, fix #2636, fix #3441, fix #3434, fix #3455

refactor(transition): refactor requestAnimationFrame with selectorQuery to improve performance

---

packages/tabs/index.ts
packages/tabs/index.wxml

fix(tab): rollback line style refactor

---

package.json
tsconfig.json
yarn.lock

feat(icons): update @vant/icons to 1.2.5

---

dist/submit-bar/index.js

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

- fix(van-submit-bar)：show undefined  when price is 0

---

packages/collapse-item/index.ts

fix(collapse): avoid use animation when height is 0

---

packages/empty/README.md
packages/empty/index.less
packages/empty/index.wxml

fix(empty): support slot

---

example/pages/tree-select/config.js
example/pages/tree-select/index.js
example/pages/tree-select/index.wxml
packages/tree-select/README.md
packages/tree-select/index.ts
packages/tree-select/index.wxml

feat(tree-select): add new prop selected-icon & badge & dot

---

package.json
yarn.lock

build(icons): update @vant/icons

---

packages/common/utils.ts
packages/tabs/index.ts
packages/tabs/index.wxml
packages/tabs/index.wxs

fix(tab): line-width support string

---

packages/dialog/dialog.ts

fix(dialog): adjust type definition

---

packages/uploader/index.less

perf(uploader): expand delete button area

---

packages/common/style/var.less
packages/nav-bar/index.less
packages/nav-bar/index.ts
packages/nav-bar/index.wxml
packages/nav-bar/index.wxs

fix(nav-bar): fix --nav-bar-icon-color not work & fix wrong style without title

---

packages/common/style/mixins/hairline.less

fix(button): fix hairline position

---

packages/common/style/var.less
packages/goods-action-icon/index.less
packages/goods-action-icon/index.wxml
packages/goods-action/index.less

fix(goods-action): add several css variable

---

packages/tabs/index.less
packages/tabs/index.wxs

fix(tab): refactor animation without transform

---

packages/swipe-cell/index.ts
packages/swipe-cell/index.wxml

feat(swipe-cell): add external-class

---

packages/notice-bar/index.ts

fix(notice-bar): adjust scrollable behavior

---

packages/field/index.wxml

fix(field): fix label-class when use label prop

---

packages/picker/index.ts

fix(picker): recover emit

---

packages/field/index.wxml

fix(field): fix empty label render

---

.github/workflows/sync.yml

同 https://github.com/youzan/vant/pull/7598

fix: add deploy branch `gh-pages`

---

packages/notify/index.less

- feat(notify): The resolution notify component is not globally centered

feat: The resolution notify component is not globally centered

---

packages/tabs/index.ts

fix(tab): correct line position in complete mode

---

packages/info/index.less

fix(info): text vertical middle in android

---

packages/datetime-picker/index.ts

示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor

fix(datetime-picker): 修复year-month 选择字段校验报错

---

packages/tabbar-item/index.ts
packages/tabbar-item/index.wxml
packages/tabbar/README.md
packages/tabbar/index.ts
packages/tabbar/index.wxml

feat(tabbar): add new props placeholder & icon-prefix

---

packages/uploader/index.less

feat(uploader): support css variables

---

example/pages/progress/index.wxml
packages/progress/README.md
packages/progress/index.less
packages/progress/index.ts
packages/progress/index.wxml
packages/progress/index.wxs
packages/wxs/add-unit.wxs
packages/wxs/bem.wxs
packages/wxs/memoize.wxs
packages/wxs/style.wxs
packages/wxs/utils.wxs

fix(progress): improve pivot position

---

packages/nav-bar/index.ts
packages/nav-bar/index.wxs
packages/wxs/style.wxs

fix(nav-bar): prevent getRect

---

packages/info/index.less
packages/info/index.wxml

fix(info): fix style error

---

packages/area/index.ts
packages/area/index.wxml
packages/area/index.wxs

fix(area): support areaList without county_list

---

packages/collapse-item/animate.ts
packages/collapse-item/index.ts
packages/collapse/index.ts
packages/common/version.ts

perf(collapse): use animate to improve performance

---

packages/goods-action/index.less

fix(goods-action): set box-sizing to keep height

---

lib/slider/index.js
packages/slider/index.ts

自定义等分时，滑动需按照自定义等分的距离触发步进
fix(slider)：自定义等分时，滑动需按照自定义等分的距离触发步进

自定义等分时，滑动需按照自定义等分的距离触发步进

---

packages/slider/index.ts

fix(slider): keep slide move evenly

---

packages/button/index.wxml
packages/button/index.wxs

fix(button): fix custom-style error

---

packages/dialog/README.md

docs(dialog): correct confirm-button-color

---

packages/swipe-cell/index.ts

perf(swipe-cell): avoid useless animate

---

README.md
docs/markdown/quickstart.md
packages/action-sheet/README.md
packages/button/README.md
packages/dialog/README.md
packages/goods-action/README.md

docs: update the url of mini program development document

---

packages/tabbar/README.md

docs(tabbar): replace minicode

---

packages/uploader/index.ts
packages/uploader/index.wxml

feat(uploader): support preview file

---

packages/mixins/transition.ts

refactor(transition): no longer throw error in wrong status

---

packages/mixins/transition.ts

fix(transition): do not display when show is true

---

example/pages/radio/index.wxml
packages/radio-group/index.less
packages/radio-group/index.ts
packages/radio-group/index.wxml
packages/radio/README.md
packages/radio/index.less
packages/radio/index.wxml

feat(radio): add new prop direction

---

packages/dialog/dialog.ts

https://github.com/youzan/vant-weapp/issues/4018

fix(Dialog): "beforeClose" missing parameter declaration

---

dist/action-sheet/index.wxml

增加前缀 （item.）否则 lang, sessionFrom 等设置无效

bugfix(ActionSheet): 修复开放能力无效

---

packages/checkbox/index.ts
packages/checkbox/index.wxml

fix(checkbox): fix label-position not work

---

packages/notice-bar/README.md
packages/notice-bar/index.ts
packages/notice-bar/index.wxml

feat(notice-bar): add default slot

---

example/pages/stepper/index.wxml
packages/common/style/var.less
packages/stepper/README.md
packages/stepper/index.less
packages/stepper/index.ts
packages/stepper/index.wxml

feat(stepper): add new prop theme & add new slot

---

packages/area/README.md

docs: fix the url of  'area.js'

---

example/pages/rate/index.wxml
packages/rate/index.ts

#4189 
- 目前不清楚如何进行单测
- 手动测试半星prop可以选择半星
- bind:change事件 & model:value 正常返回value

fix(Rate): support touch move and selected half star

---

packages/calendar/README.md

docs(calendar): fix typo

---

example/pages/icon/index.wxss
package.json
yarn.lock

https://github.com/youzan/vant-weapp/issues/3997

feat(Icons): migrate all icons to iconfont.cn

---

packages/circle/index.ts

fix(circle): Fix the bug of shake when the circle component value is a decimal number.
fix #3373

fix(circle): Fix the bug of shake when the circle component value is a decimal number.

---

packages/action-sheet/index.wxml
packages/button/index.wxml

fix(button): fix open-type not work

---

packages/calendar/README.md
packages/calendar/index.ts

#4181 
- forbid range-prompt toast when range-prompt prop is null
- emit over-range event when dateRange > maxRange

feat(Calendar): add over-range event

---

example/pages/calendar/index.js
example/pages/calendar/index.wxml
packages/calendar/README.md
packages/calendar/calendar.wxml
packages/calendar/components/header/index.ts
packages/calendar/components/month/index.ts
packages/calendar/components/month/index.wxml
packages/calendar/components/month/index.wxs
packages/calendar/index.ts

feat: [#4211](https://github.com/youzan/vant-weapp/issues/4211)、[#3552](https://github.com/youzan/vant-weapp/issues/3552)、[#3636](https://github.com/youzan/vant-weapp/issues/3636)

feat(calendar): synchronize the vant calendar component, and add the attribute of custom week starting from the day of the week (#4211)

---

packages/tabs/index.ts
packages/tabs/index.wxml

fix(tabs): remove duplicated init offset

---

example/pages/uploader/index.js

uploader demo 的 beforeRead 函数有问题，file 对象上没有 path 属性，会导致调用的时候报错，更正为 url

fix(uploader): fix uploader demo for beforeRead function

---

packages/datetime-picker/index.ts

fix(DatetimePicker): fix incorrect columns index

---

example/pages/share-sheet/index.js
packages/share-sheet/README.md
packages/share-sheet/options.wxs

fix(share-sheet): add icons

---

example/pages/checkbox/index.js
example/pages/checkbox/index.wxml
packages/checkbox-group/index.less
packages/checkbox-group/index.ts
packages/checkbox-group/index.wxml
packages/checkbox/README.md
packages/checkbox/index.less
packages/checkbox/index.ts
packages/checkbox/index.wxml

feat(Checkbox): add direction prop

---

packages/icon/README.md

docs(Icon): add custom iconfont

---

packages/wxs/style.wxs

支持在wxml中使用驼峰命名style属性名
```html
<wxs src="../wxs/style.wxs" module="style" />
<view style="{{ style({ fontSize: '12px' }) }}">text</view>
```

feat(wxs): style.wxs support camel case attr

---

packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/README.md

feat(GridItem): add icon-prefix prop

---

packages/grid-item/index.less
packages/grid-item/index.ts
packages/grid-item/index.wxml
packages/grid/README.md
packages/grid/index.ts

feat(Grid): add reverse prop

---

example/pages/rate/index.js
example/pages/rate/index.wxml
packages/common/style/var.less
packages/rate/README.md
packages/rate/index.less
packages/rate/index.ts
packages/rate/index.wxml

- 支持与vant相同的css变量
- 调整文档格式
- 移除 `prop.color` `prop.voidColor` `prop.disabledColor` 默认颜色
- 使用 `bem` 优化className
- 使用 `utils.style` 优化style属性

feat(Rate): css variables

---

packages/common/utils.ts
packages/index-bar/index.ts

fix(IndexBar): sidebar not exists

---

packages/calendar/index.ts
packages/calendar/utils.ts

#4288 
和vant `getInitialDate` 相同逻辑

fix(Calendar): set current date is inital

---

example/pages/cell/index.wxml
packages/cell-group/index.less
packages/cell-group/index.ts
packages/cell-group/index.wxml
packages/cell/README.md
packages/common/style/var.less

feat(Cell): cell-group inset prop
