youzan/vant-weapp

example/pages/tab/index.js, example/pages/tab/index.wxml, packages/helper/README.md, packages/tab/README.md, packages/tab/index.pcss, packages/tab/index.wxml
- 修复 tab 组件在不滚动情况下，文字过长直接截取问题，改为点点点模式
- 修改 tab 组件参数传入方式，兼容老的数据传入
- 增加 helper 文档
=> [bug fix] Tab: 修复不滚动情况下，文字过长显示问题

example/pages/btn/index.json, example/pages/btn/index.wxml, example/pages/tag/index.json, example/pages/tag/index.wxml, example/pages/tag/index.wxss, packages/btn/index.js, packages/btn/index.json, packages/btn/index.pcss, packages/btn/index.wxml, packages/tag/index.js, packages/tag/index.json, packages/tag/index.wxml
* [breaking change] zan-tag: 改为微信自定义组件
* [breaking change] zan-button: 改为微信自定义组件
- tag改为微信自定义组件，可通过属性type、plain、disabled来控制显示样式
- button改为微信自定义组件，可通过属性type、size、disabled、loading来控制显示样式
=> [refactor] 完成button、tag自定义组件改造

example/pages/switch/index.wxml
- 修复示例中，关于异步 ```Switch```组件 的名称错误
=> [bugfix] Switch：修复组件示例名称错误

packages/stepper/index.js
case:
html
```html
<zan-stepper stepper="{{ value }}" min="0" max="100" step="0.2" bindchange="handleChange" />
```
js
```js
Page({
data: {
value: 0.1
},
handleChange...
});
```
=> fixed when step is a decimals sometimes

example/components/doc-page/index.wxml, example/pages/card/index.wxml
- [bugfix] Doc: Card 示例页 title 标注错误为 CAPSULE
- [improvement] Doc: 统一 title 为大写
=> [bugfix] Doc: Card 示例页 title 标注错误为 CAPSULE

packages/field/README.md, packages/field/index.ts
- 增加事件 `focus` 回调参数： `value` 当前输入值， `height` 键盘高度(在基础库 1.9.90 起支持)
- 增加事件 `blur` 回调参数： `value` 当前输入值， `cursor` 游标位置(如果 `type` 不为 `textarea`，值为 `0`)
=> [new feature] Field: 增加事件 `focus`, `blur` 回调参数

packages/steps/index.less
[bugfix] steps：修复index.less中底部边框选择器在微信开发者工具中运行“自动运行体验评分”css选择器报错
修复 #1013 
- 改动一更改&--vertical选择器
=> 修复steps样式组件

packages/dialog/index.ts
- [packages/dialog/index.ts]第94行
this.$emit(action); 改成：
//把dialog实例传递出去，可以通过stopLoading()在外部关闭按钮的loading
this.$emit(action, {dialog: this});
=> [improvement] dialog表单组件：可以使用传递出的dialog实例的stopLoading()手动关闭按钮的loading状态

packages/stepper/index.ts
我尝试了两种修复方式，不确定哪一种会更符合 vant 的设计，所以希望提交两个 PR，请你们帮忙选择。
When the stepper has value '1' and the user tries to edit the value
directly to '50', the input field stop user from delete '1' to ''.
The reason for the bug is `props: { value: Number }` trying to
convert empty string to 0, then `watch: { value() {} }` will set 0
to 1 automatically.
This fix tries to:
* allow type String for `value` to support empty string ''
* stop convert '' to 0 from the watcher
The bug was introduced from 696ae3c.
Resolves: #1151
=> [Bugfix] Stepper: allow delete input to empty (solution 1)

example/pages/popup/index.js, example/pages/popup/index.wxml, packages/popup/README.md, packages/popup/index.ts
假设现在有一个需求，我们的 `ListItem` 具有触发 PopUp 的能力。有两种方式可以做到：
1. 在 `ListItem` 中声明 `Popup`，通过 `wx:if` 来做到性能优化。
2. 在 `ListItem` 的父组件，比如 `List` 中声明，通过在 `ListItem`  中 `triggerEvent` 来发生 `PopUp` 所需要的数据。
第二种方式目前常用的方式，因为如果直接用 `wx:if` 判断的话，关闭 `Popup` 时没有动画，导致整个过程很生硬。而现有的生命周期又不满足需求，所以通过在 `transtion` 后，将 `wx:if` 改为 false 就能拿到效果。
虽然我们可以继续使用第二种方式，但是它很容易让 `List` 变成一个非常庞大的组件。这里有一个 `Popup`，那里又有一个 `Popup`，不知不觉就变成了 `PopUp` 中转站。所以，通过添加这个事件，可以在一定程序上减少对 `List` 的依赖。更关注 `ListItem` 本身。
=> Popup 添加 `transitionEnd` 事件

packages/search/index.ts
#1768 
修复修改 输入框 值时，赋值和输入框失焦时间同时触发，改值无效。
可能是是小程序 bug
=> [bugfix] Field: Modified value invalid

packages/collapse-item/index.ts
修复 #1817 。
- collapse-item组件初次挂载完成，如果默认为展开则高度改为auto（手动执行一下onTransitionEnd方法）
=> [bugfix] Collapse: 默认展开情况下动态增加内容高度自适应

dist/area/index.js, packages/area/index.ts
=> [bug fix] Area: 修复area组件，当columns-num等于2时，设置value，第一项省级永远显示北京市

packages/info/index.wxml
https://github.com/youzan/vant-weapp/issues/1882
=> [fix] Icon: should not render info when value is empty string

packages/checkbox/index.less, packages/goods-action-button/index.ts
设置 `icon-size` 为小像素时，由于子元素 `inline-block` 导致的样式bug
=> fix(checkbox): set a 12px icon size style bug

dist/progress/index.js, dist/progress/index.wxml
- feat(van-progress)：Add the customizable track color of van-progress, users now can set param 'trackColor' to designated color to change the track color.
示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> feat(van-progress): Add customizable progress track color

packages/tabbar-item/index.less
由于微信小程序禁止使用标签选择器，因此移除了 Tabbar 内部的标签选择器样式，由用户自行控制
=> breaking change(tabbar): remove tag selector

example/pages/tree-select/index.wxml, packages/common/style/var.less, packages/icon/index.less, packages/image/index.wxml, packages/sidebar-item/index.less, packages/sidebar-item/index.ts, packages/sidebar-item/index.wxml, packages/sidebar/index.less, packages/sidebar/index.ts, packages/tree-select/index.json, packages/tree-select/index.less, packages/tree-select/index.ts, packages/tree-select/index.wxml
BREAKING CHANGE: rename prop active of sidebar to activeKey
TreeSelect
- refactor component with sidebar
- support css variables
SideBar
- rename prop `active` to `activeKey`
- support css variables
SideBarItem
- add new prop `disabled`
- add new external classes `active-class` & `disabled-class`
- support css variables
Icon
- add host style to keep icon centered
=> refactor(TreeSelect): refactor with sidebar @rex-zsd

packages/notice-bar/index.wxml
=> fix(NoticeBar): catch tap event of close icon @rex-zsd

packages/tabs/index.ts, packages/tabs/index.wxml
tabs选项卡当使用吸顶sticky功能时，没有scroll事件。
=> fix(Tabs): 修复选项卡竖向滚动时触发scroll事件

example/pages/search/index.js, example/pages/search/index.wxml, packages/search/README.md
docs(Search): 修改自定义按钮绑定的处理函数，更新组件 search 事件的含义 
fix #2447
=> docs(Search): fix demo problem

package.json, yarn.lock
https://github.com/youzan/vant-weapp/issues/2437
适逢 1.0 发布，不再兼容错误拼写的用法
=> fix(Icon): medal typo

packages/uploader/README.md, packages/uploader/index.ts
feat(Uploader): add sizeType Attribute
fix: #2530
=> feat(Uploader): add sizeType Attribute

package.json
在使用过程中,如果不使用开发工具的es5转es6功能,语法报错.
不使用开发工具的原因是开发工具在转的时候用的babel的方式,会在某些情况下会出错(我使用的情况比较复杂一些,对于出错的情况不太好解释,总之这个功能鸡肋得很).所以我不能在项目中开启es6到es5的转化.
我搞不懂的是有赞的这个包为什么这么设计,既然用ts开发的代码,直接target设成es5编译不就什么事都没有了,为什么还要在lib目录之外,编译一个es6的版本出来,并且还让微信小程序的开发工具在构建的时候使用es6的版本.我看了源码并且考虑过,实在是没能够想明白.
=> fix: use lib as miniprogram

lib/tabs/index.js
解决动态添加tabs列表内容时，顺序错乱以及下划线长度不变的问题。
Fix #2604 & #2661
=> fix #2604 & #2661 解决动态添加tabs列表内容时，顺序错乱以及下划线长度不变的问题。

packages/button/README.md, packages/button/index.ts, packages/button/index.wxml
=> feat(button): add new prop dataset

packages/calendar/index.ts
=> fix(calendar): 在多选日期状态下,选择完后点确定提交报错

packages/uploader/README.md, packages/uploader/index.ts, packages/uploader/index.wxml
uploader组件，deletable属性只能控制全局是否可以删除，不能控制单张图片是否可删除；因此当fileList内为对象时，增加onlyRead标识，当onlyRead为true时，单张不显示删除icon。
=> fix:uploader组件增加单张只读属性

dist/calendar/index.js, dist/datetime-picker/index.js
fix(datetime-picker): 默认值为string 解析时间错误
fix(calendar): confirmDisabledText增加默认值和文档同步
datetime-picker 文档描述
实例传入String值报错截图
calendar 示例默认值
=> fix(calendar): confirmDisabledText增加默认值和文档同步

example/pages/uploader/index.js, packages/common/utils.ts, packages/common/validator.ts, packages/uploader/README.md, packages/uploader/index.ts, packages/uploader/index.wxml, packages/uploader/utils.ts
=> feat(uploader): add new key thumb & standardization file-list

packages/field/index.wxml
fix(Field): Clicking on the keyboard to associate words causes the current number of words to exceed the limit, but the actual number does not exceed
Disconnect the real machine for debugging
=> fix(Field): showWordLimit value.length > maxlength

example/components/demo-block/index.js, example/components/demo-block/index.wxml, example/components/demo-block/index.wxss, example/pages/dialog/index.js, example/pages/dialog/index.wxml, packages/common/utils.ts, packages/dialog/README.md, packages/dialog/dialog.ts, packages/dialog/index.ts
=> feat(Dialog): add new prop beforeClose

packages/popup/index.wxml, packages/popup/index.wxs, packages/sticky/index.wxs, packages/tab/README.md, packages/tabs/index.ts, packages/tabs/index.wxml, packages/tabs/index.wxs, packages/wxs/style.wxs
=> perf(tab): improve wxs style assemble & export resize methods

docs/markdown/quickstart.md
目前新版开发者工具创建的小程序目录文件结构问题，npm构建的文件目录为miniprogram_npm，并且开发工具会默认在当前目录下创建miniprogram_npm的文件名，所以新版本的miniprogramNpmDistDir配置为'./'即可
示例：
可选择的类型:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs(quickstart):修复文档快速开始适配新版小程序开发者工具

example/pages/calendar/index.js
In wxs file, `getDate(datestring)` return an error 'Invalid Date' in phone device, using `getDate(milliseconds)` replace it
=> fix(Calendar): display 'NaN/NaN/NaN' in phone device after select date

packages/common/utils.ts, packages/common/version.ts, packages/dropdown-menu/index.ts, packages/index-anchor/index.ts, packages/index-bar/index.ts, packages/nav-bar/index.ts, packages/notice-bar/index.ts, packages/progress/index.ts, packages/rate/index.ts, packages/slider/index.ts, packages/sticky/index.ts, packages/tabbar/index.ts, packages/tabs/index.ts
=> fix(tab): use groupSetData to keep tab render sync

packages/tabs/index.ts
fix(tabs)：修复tabs在初始化的时候active的值被tabs的默认值给覆盖掉的问题
=> [fix]:修复tabs在初始化的时候active的值被tabs的默认值给覆盖掉的问题

packages/picker-column/index.wxml
computed.wrapperStyle needs duration parameter, otherwise it will generate undefined value for transition style property
=> fix(picker-column)：undefined style value 

packages/calendar/components/month/index.wxs
#4162
自定义颜色未能覆盖：`allow-same-day` 开启时，选中同一天时的按钮颜色。
正常的效果
未覆盖到的效果
Bug 复现：
1. 使用默认的 ”自定义颜色“ 示例
1. 开启 `allow-same-day` 选项
1. 选中同一天后，颜色还是默认色，而不是覆盖的自定义颜色；而其他天数均正常
此 PR 实现的效果：
=> fix(calendar): fix custom color for same-day button

packages/button/index.ts
Button 组件获取微信用户信息时，type 属性 为 getUserInfo 并且 wx.getUserProfile 可用时，设置 lang 属性无效，获取到的用户信息一直为英文。
=> fix(button): 修复type为getUserInfo且wx.getUserProfile可用时，lang参数无效问题

example/app.json, example/config.js, example/pages/config-provider/index.js, example/pages/config-provider/index.json, example/pages/config-provider/index.wxml, example/project.config.json, packages/config-provider/README.md, packages/config-provider/index.json, packages/config-provider/index.ts, packages/config-provider/index.wxml, packages/config-provider/index.wxs, vant.config.js
增加ConfigProvider组件
和vant的差异
- **部分变量定义不生效** 目前vant-weapp部分组件样式是通过style写死的，例如 `rate` 组件中用到的默认color，导致虽然在config-provider中配置了 `rateIconFullColor`也不生效，需要继续优化
- **无css基础变量** vant-weapp并没有像vant一样的基础css 变量库，而是通过 `.theme()` 将less var提取出来替换成var(--xxx, default-style)形式，需要继续优化
- **无法使用:root全局替换** 小程序通过在 `page {}` 中生命css变量进行全局css变量替换
- **css变量名不同** vant-weapp没有--van前缀，例如vant中是 `--van-black`，而 vant-weapp中是 `--black`
=> feat(ConfigProvider): add config-provider component

packages/grid-item/index.ts
=> fix(griditem): set icon prefix to 'van-icon'
